version: "3.8"

services:
  react-app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true # Enable webpack polling
      - FAST_REFRESH=false # Disable fast refresh temporarily
      - WDS_SOCKET_PORT=3000 # Specify WebSocket port